const ENDPOINTS = {
  login: "login",
  register: "register",
  verifyOtp: "verify-otp",
  resendOtp: "resend-otp",
  forgotPassword: "forget-password",
  verifyResetOtp: "verify-reset-otp",
  resetPassword: "reset-password",
  socialLogin: "/social-login",
  buyPlan: "user/plans",
  buyAgain: "user/buy-again",
  setUpIntent: "user/setup-intent",
  userInfo: "user/user-more-info",
  getPlans: "user/plans",

  // Payment
  createSetupIntent: "user/setup-intent",

  // Paid Endpoints
  getUSerData: "user/get-user",
  getMoodData: "paid-user/mood",
  toggleJournal: "paid-user/toggle/journal-encryption",
  changePassword: "paid-user/change-password",
  suppotRequest: "paid-user/support",
  updateUser: "paid-user/update-user",
  updateSubscription: "paid-user/update-subscription",
  getSubscriptionDetails: "paid-user/subscription",
  deleteAccount: "paid-user/delete-account",
  sendmessage: "paid-user/chat-gpt",
  getMessages: "paid-user/chat-gpt",
  getHomeData: "paid-user/home",
  mood: "paid-user/mood",
  getMyJournalList: "paid-user/journal",
  createJournal: "paid-user/journal",
  getDailyReflection: "paid-user/user/daily-reflection",
  getReflectionbyId: "paid-user/daily-reflection",
  updateReflection: "paid-user/daily-reflection",
  getJournalbyId: "paid-user/journal",
  checkCompatibility: "paid-user/compatibility",
  getAllCompatibleUsers: "paid-user/compatibility",
  checkJournalPssword: "paid-user/toggle/journal-encryption",
  generateHoroscope: "paid-user/generate-horoscope",
  deleteCompatibilityProfile: "paid-user/compatibility",
  getTileData: "paid-user/guide/",
  saveSubscriptioData: "user/create-subscription",
  restorePurchase: "user/restore-purchase",
  validateIosReciept: "user/validate-ios-receipt",
};

export default ENDPOINTS;
